///footer data
export const tools = [
  "HTML",
  "CSS/SCSS",
  "JavaScript",
  "TypeScript",
  "React.js",
  "Next.js",
  "Tailwind CSS",
  "WordPress",
  "WooCommerce",
  "Git",
  "GitHub",
  "VSCode",
  "OVH",
  "AWS",
  "Azure",
  "FileZilla",
];
export const categories = {
  "Front-end": [
    "HTML",
    "CSS / SCSS",
    "JavaScript",
    "TypeScript",
    "React.js",
    "Next.js",
    "Tailwind CSS",
  ],
  "Back-end & API": ["Node.js", "REST API", "MongoDB", "SQL"],
  "CMS & Emailing": ["WordPress", "WooCommerce", "Mailchimp"],
  "Design & UX": ["Figma", "Photoshop", "Canva"],
  "Outils & Déploiement": [
    "Git",
    "GitHub",
    "VSCode",
    "OVH",
    "AWS",
    "Azure",
    "FileZilla",
  ],
  "Méthodologie & Gestion": [
    "Trello",
    "Notion",
    "Agile",
    "User Stories",
    "Kanban",
  ],
};
